// <auto-generated/>
// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

#if DEBUG

namespace Microsoft.CodeAnalysis
{
    /* This is no longer valid, FileTextLoader is now in Microsoft.CodeAnalysis.Workspaces.Common!
    /// <summary>
    /// This class will fail to compile (CS0419 Ambiguous reference in cref attribute) if the project contains a
    /// reference to Microsoft.CodeAnalysis.Workspaces.Desktop.
    /// </summary>
    /// <see cref="FileTextLoader"/>
    internal class EnsureNoWorkspacesDesktopReference
    {
    }
    */
}

#endif
