pr:
- main

variables:
- template: /eng/common/templates/variables/pool-providers.yml

pool:
  name: $(DncEngPublicBuildPool)
  demands: ImageOverride -equals windows.vs2026.amd64.open

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    useGlobalJson: true
    includePreviewVersions: true
