<Project>
  <ItemGroup>
    <PackageVersion Include="CsvTextFieldParser" Version="1.2.2-preview" />
    <PackageVersion Include="DiffPlex" Version="$(DiffPlexVersion)" />
    <PackageVersion Include="EnvDTE" Version="$(EnvDTEVersion)" />
    <PackageVersion Include="Handlebars.Net" Version="1.10.1" />
    <PackageVersion Include="MessagePack" Version="$(MessagePackVersion)" />
    <PackageVersion Include="Microsoft.Build" Version="17.5.0" />
    <PackageVersion Include="Microsoft.Build.Locator" Version="1.5.3" />
    <PackageVersion Include="Microsoft.Build.Tasks.Core" Version="$(MicrosoftBuildTasksCoreVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis" Version="4.0.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="$(MicrosoftCodeAnalysisAnalyzersVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Common" Version="$(MicrosoftCodeAnalysisCommonVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="$(MicrosoftCodeAnalysisCSharpVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" Version="$(MicrosoftCodeAnalysisTestingVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.CodeFix.Testing" Version="$(MicrosoftCodeAnalysisTestingVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.0.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.EditorFeatures.Text" Version="$(MicrosoftCodeAnalysisEditorFeaturesTextVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.VisualBasic" Version="$(MicrosoftCodeAnalysisVisualBasicVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.VisualBasic.Analyzer.Testing" Version="$(MicrosoftCodeAnalysisTestingVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.VisualBasic.CodeFix.Testing" Version="$(MicrosoftCodeAnalysisTestingVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.VisualBasic.Workspaces" Version="4.0.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="1.0.1" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.0.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="2.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="2.0.0" />
    <PackageVersion Include="Microsoft.IO.Redist" Version="$(MicrosoftIORedistVersion)" />
    <PackageVersion Include="Microsoft.ServiceHub.Framework" Version="$(MicrosoftServiceHubFrameworkVersion)" />
    <PackageVersion Include="Microsoft.VisualBasic" Version="10.0.1" />
    <PackageVersion Include="Microsoft.VisualStudio.ComponentModelHost" Version="$(MicrosoftVisualStudioComponentModelHostVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.Composition" Version="$(MicrosoftVisualStudioCompositionVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.CoreUtility" Version="$(MicrosoftVisualStudioCoreUtilityVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.Editor" Version="$(MicrosoftVisualStudioEditorVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.Extensibility.Testing.SourceGenerator" Version="$(MicrosoftVisualStudioExtensibilityTestingSourceGeneratorVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.Extensibility.Testing.Xunit" Version="$(MicrosoftVisualStudioExtensibilityTestingXunitVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.ImageCatalog" Version="$(MicrosoftVisualStudioImageCatalogVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.Imaging" Version="$(MicrosoftVisualStudioImagingVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime" Version="$(MicrosoftVisualStudioImagingInterop140DesignTimeVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.Interop" Version="$(MicrosoftVisualStudioInteropVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.Language.StandardClassification" Version="$(MicrosoftVisualStudioLanguageStandardClassificationVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.ProjectSystem.Managed" Version="$(MicrosoftVisualStudioProjectSystemManagedVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.ProjectSystem.Managed.VS" Version="$(MicrosoftVisualStudioProjectSystemManagedVSVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.ProjectSystem.SDK.Tools" Version="$(MicrosoftVisualStudioProjectSystemSDKToolsVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.SDK.Analyzers" Version="$(MicrosoftVisualStudioSDKAnalyzersVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.Shell.15.0" Version="$(MicrosoftVisualStudioShell150Version)" />
    <PackageVersion Include="Microsoft.VisualStudio.Shell.Interop" Version="$(MicrosoftVisualStudioShellInteropVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.Shell.Interop.8.0" Version="$(MicrosoftVisualStudioShellPackagesVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.TemplateWizardInterface" Version="$(MicrosoftVisualStudioTemplateWizardInterfaceVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.Text.Data" Version="$(MicrosoftVisualStudioTextDataVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.Text.Logic" Version="$(MicrosoftVisualStudioTextLogicVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.Text.UI.Wpf" Version="$(MicrosoftVisualStudioTextUIWpfVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.TextManager.Interop.8.0" Version="$(MicrosoftVisualStudioTextManagerInterop80Version)" />
    <PackageVersion Include="Microsoft.VisualStudio.Threading" Version="$(MicrosoftVisualStudioThreadingVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.Threading.Analyzers" Version="$(MicrosoftVisualStudioThreadingAnalyzersVersion)" />
    <PackageVersion Include="Microsoft.VisualStudio.Utilities.Internal" Version="$(MicrosoftVisualStudioUtilitiesInternalVersion)" />
    <PackageVersion Include="Microsoft.Visualstudio.Validation" Version="$(MicrosoftVisualStudioValidationVersion)" />
    <PackageVersion Include="Moq" Version="4.7.142" />
    <PackageVersion Include="Newtonsoft.Json" Version="$(NewtonsoftJsonVersion)" />
    <PackageVersion Include="NuGet.Common" Version="$(NuGetApiVersion)" />
    <PackageVersion Include="NuGet.Packaging" Version="$(NuGetApiVersion)" />
    <PackageVersion Include="NuGet.Protocol" Version="$(NuGetApiVersion)" />
    <PackageVersion Include="NuGet.Resolver" Version="$(NuGetApiVersion)" />
    <PackageVersion Include="NuGet.SolutionRestoreManager.Interop" Version="$(NuGetSolutionRestoreManagerInteropVersion)" />
    <PackageVersion Include="Nullable" Version="1.3.0" />
    <PackageVersion Include="Roslyn.Diagnostics.Analyzers" Version="$(RoslynDiagnosticsAnalyzersVersion)" />
    <PackageVersion Include="StreamJsonRpc" Version="$(StreamJsonRpcVersion)" />
    <PackageVersion Include="System.Collections.Immutable" Version="$(SystemCollectionsImmutable10Version)" />
    <PackageVersion Include="System.Composition" Version="1.1.0" />
    <PackageVersion Include="System.Formats.Asn1" Version="$(SystemFormatsAsn1Version)" />
    <PackageVersion Include="System.Memory" Version="$(SystemMemoryVersion)" />
    <PackageVersion Include="System.Net.Http" Version="$(SystemNetHttpVersion)" />
    <PackageVersion Include="System.Reflection.Metadata" Version="1.6.0" />
    <PackageVersion Include="System.Runtime.CompilerServices.Unsafe" Version="$(SystemRuntimeCompilerServicesUnsafeVersion)" />
    <PackageVersion Include="System.Security.Cryptography.X509Certificates" Version="4.3.0" />
    <PackageVersion Include="System.Text.Json" Version="$(SystemTextJsonVersion)" />
    <PackageVersion Include="System.Threading.Tasks.DataFlow" Version="$(SystemThreadingTasksDataflowVersion)" />
    <PackageVersion Include="System.Threading.Tasks.Extensions" Version="$(SystemThreadingTasksExtensionsVersion)" />
    <PackageVersion Include="System.ValueTuple" Version="4.5.0" />
    <PackageVersion Include="VSLangProj" Version="$(VSLangProjVersion)" />
    <PackageVersion Include="xunit.assert" Version="$(XunitVersion)" Condition="'$(MSBuildProjectName)' == 'Microsoft.CodeAnalysis.Testing.Utilities' or '$(MSBuildProjectName)' == 'Roslyn.UnitTestFramework'" />
    <PackageVersion Include="Xunit.Combinatorial" Version="$(XunitCombinatorialVersion)" />
  </ItemGroup>
</Project>
